"""Add airport and route models, update fare model

Revision ID: d94f369a4b6d
Revises: 
Create Date: 2026-09-10 09:59:39.159879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94f369a4b6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('airport_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('airport_id')
    )
    op.create_index(op.f('ix_airports_airport_id'), 'airports', ['airport_id'], unique=False)
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=True)
    op.create_index(op.f('ix_airports_icao_code'), 'airports', ['icao_code'], unique=False)
    op.create_table('fare_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=True),
    sa.Column('destination', sa.String(length=3), nullable=True),
    sa.Column('route', sa.String(length=7), nullable=True),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('observation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('advance_purchase_days', sa.Integer(), nullable=False),
    sa.Column('fare_class', sa.String(length=50), nullable=True),
    sa.Column('base_fare', sa.Float(), nullable=True),
    sa.Column('taxes', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('airport_fees', sa.Float(), nullable=True),
    sa.Column('udf', sa.Float(), nullable=True),
    sa.Column('convenience_charge', sa.Float(), nullable=True),
    sa.Column('total_fare', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stops', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('availability_count', sa.Integer(), nullable=True),
    sa.Column('data_status', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('raw_data_reference', sa.String(length=255), nullable=True),
    sa.Column('cleaned_value', sa.Float(), nullable=True),
    sa.Column('outlier_flag', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fare_observations_advance_purchase_days'), 'fare_observations', ['advance_purchase_days'], unique=False)
    op.create_index(op.f('ix_fare_observations_airline'), 'fare_observations', ['airline'], unique=False)
    op.create_index(op.f('ix_fare_observations_data_status'), 'fare_observations', ['data_status'], unique=False)
    op.create_index(op.f('ix_fare_observations_id'), 'fare_observations', ['id'], unique=False)
    op.create_index(op.f('ix_fare_observations_observation_timestamp'), 'fare_observations', ['observation_timestamp'], unique=False)
    op.create_index(op.f('ix_fare_observations_route'), 'fare_observations', ['route'], unique=False)
    op.create_index(op.f('ix_fare_observations_source'), 'fare_observations', ['source'], unique=False)
    op.create_index(op.f('ix_fare_observations_source_type'), 'fare_observations', ['source_type'], unique=False)
    op.create_index(op.f('ix_fare_observations_travel_date'), 'fare_observations', ['travel_date'], unique=False)
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('origin_airport_id', sa.Integer(), nullable=True),
    sa.Column('destination_airport_id', sa.Integer(), nullable=True),
    sa.Column('origin_code', sa.String(length=3), nullable=False),
    sa.Column('destination_code', sa.String(length=3), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('route_type', sa.String(length=50), nullable=True),
    sa.Column('statistical_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_destination_airport_id'), 'routes', ['destination_airport_id'], unique=False)
    op.create_index(op.f('ix_routes_destination_code'), 'routes', ['destination_code'], unique=False)
    op.create_index(op.f('ix_routes_origin_airport_id'), 'routes', ['origin_airport_id'], unique=False)
    op.create_index(op.f('ix_routes_origin_code'), 'routes', ['origin_code'], unique=False)
    op.create_index(op.f('ix_routes_route_id'), 'routes', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_route_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_origin_code'), table_name='routes')
    op.drop_index(op.f('ix_routes_origin_airport_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_code'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_airport_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_fare_observations_travel_date'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_source_type'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_source'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_route'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_observation_timestamp'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_id'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_data_status'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_airline'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_advance_purchase_days'), table_name='fare_observations')
    op.drop_table('fare_observations')
    op.drop_index(op.f('ix_airports_icao_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_airport_id'), table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
